version: '3.8'

services:
  python_server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: python_server
    ports:
      - "50051:50051"

  python_client:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: python_client
    depends_on:
      - python_server
    environment:
      - GRPC_SERVER_HOST=python_server