version: "3.9"

services:
  node1:
    build:
      context: .
      dockerfile: Dockerfile.node1
    ports:
      - "50051:50051"
    volumes:
      - ./data/node1:/app/data

  node2:
    build:
      context: .
      dockerfile: Dockerfile.node2
    ports:
      - "50052:50052"
    volumes:
      - ./data/node2:/app/data

  node3:
    build:
      context: .
      dockerfile: Dockerfile.node3
    ports:
      - "50053:50053"
    volumes:
      - ./data/node3:/app/data

  node4:
    build:
      context: .
      dockerfile: Dockerfile.node4
    ports:
      - "50054:50054"
    volumes:
      - ./data/node4:/app/data

  node5:
    build:
      context: .
      dockerfile: Dockerfile.node5
    ports:
      - "50055:50055"
    volumes:
      - ./data/node5:/app/data
