# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: failure_detection.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'failure_detection.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x66\x61ilure_detection.proto\x12\x04swim\" \n\x0bPingRequest\x12\x11\n\tsender_id\x18\x01 \x01(\t\"\x16\n\x07PingAck\x12\x0b\n\x03\x61\x63k\x18\x01 \x01(\x08\"1\n\x0fIndirectPingAck\x12\x11\n\ttarget_id\x18\x01 \x01(\t\x12\x0b\n\x03\x61\x63k\x18\x02 \x01(\x08\";\n\x13IndirectPingRequest\x12\x11\n\tsender_id\x18\x01 \x01(\t\x12\x11\n\ttarget_id\x18\x02 \x01(\t2}\n\x0f\x46\x61ilureDetector\x12(\n\x04Ping\x12\x11.swim.PingRequest\x1a\r.swim.PingAck\x12@\n\x0cIndirectPing\x12\x19.swim.IndirectPingRequest\x1a\x15.swim.IndirectPingAckb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'failure_detection_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PINGREQUEST']._serialized_start=33
  _globals['_PINGREQUEST']._serialized_end=65
  _globals['_PINGACK']._serialized_start=67
  _globals['_PINGACK']._serialized_end=89
  _globals['_INDIRECTPINGACK']._serialized_start=91
  _globals['_INDIRECTPINGACK']._serialized_end=140
  _globals['_INDIRECTPINGREQUEST']._serialized_start=142
  _globals['_INDIRECTPINGREQUEST']._serialized_end=201
  _globals['_FAILUREDETECTOR']._serialized_start=203
  _globals['_FAILUREDETECTOR']._serialized_end=328
# @@protoc_insertion_point(module_scope)
