FROM python:3.9-slim


WORKDIR /app

# Copy requirements and install
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt


COPY fd_node.py .
COPY swim.proto .


RUN python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. swim.proto


CMD ["python", "fd_node.py", "--port", "50051"]
